export const studentList = [
  {
    college: "Oxford College of Engineering and Management",
    studentName: "Pradeep Kunwar",
    affiliatedTo: "Pokhara University",
    level: "Bachelor",
    faculty: "Science and Technology",
    program: "BCA",
    subjects: [
      "Mathematics",
      "English",
      "Digital Logic",
      "Programming Logic",
      "Database Management",
    ],
  },
  {
    college: "Lumbini College of Information and Technology",
    studentName: "Prajeena Pokhrel",
    affiliatedTo: "Tribhuvan University",
    level: "Master",
    faculty: "Science and Technology",
    program: "MCA",
    subjects: [
      "Advanced Algorithms",
      "Machine Learning",
      "Cloud Computing",
      "Cyber Security",
      "Big Data Analytics",
    ],
  },
  {
    college: "Pulchowk College",
    studentName: "Jeena Ortega",
    affiliatedTo: "Kathmandu University",
    level: "Bachelor",
    faculty: "Management",
    program: "BBA",
    subjects: [
      "Financial Accounting",
      "Marketing Management",
      "Business Law",
      "Human Resource Management",
      "Entrepreneurship",
    ],
  },
  {
    college: "Mechi Engineering College",
    studentName: "Samir Sharma",
    affiliatedTo: "Purbanchal University",
    level: "Bachelor",
    faculty: "Engineering",
    program: "BE Civil",
    subjects: [
      "Structural Analysis",
      "Hydraulics",
      "Surveying",
      "Building Construction",
      "Transportation Engineering",
    ],
  },
  {
    college: "Kantipur City College",
    studentName: "Ritika Thapa",
    affiliatedTo: "Tribhuvan University",
    level: "Bachelor",
    faculty: "Science and Technology",
    program: "BSc CSIT",
    subjects: [
      "Artificial Intelligence",
      "Computer Networks",
      "Operating Systems",
      "Data Structures",
      "Software Engineering",
    ],
  },
  {
    college: "Himalaya College of Nursing",
    studentName: "Sneha Karki",
    affiliatedTo: "Pokhara University",
    level: "Bachelor",
    faculty: "Health Sciences",
    program: "BN",
    subjects: [
      "Anatomy",
      "Physiology",
      "Pharmacology",
      "Community Health Nursing",
      "Pediatrics Nursing",
    ],
  },
  {
    college: "Birgunj Medical College",
    studentName: "Aayush Gupta",
    affiliatedTo: "Tribhuvan University",
    level: "Bachelor",
    faculty: "Medical",
    program: "MBBS",
    subjects: [
      "General Medicine",
      "Pathology",
      "Microbiology",
      "Surgery",
      "Pharmacology",
    ],
  },
];
